package pp.game.level;

public enum LevelType {
	SURVIVAL, 
	
	// config handler
	TEST_NO_MONSTERS,
	TEST_LOW_HP_FREQUENT_SPAWN,
	
	// manual handler
	TEST_HIGH_HP_MANY_MONSTERS,
	TEST_LOW_HP_ONE_MONSTER,
	TEST_HIGH_HP_ONE_MONSTER,
	TEST_HIGH_HP_NORMAL_SPAWN,
	TEST_BONUS_SPAWN;
}
